
#' Return a list of all controls
#'
#' @param rcapConfig a list generated by jsonlite::fromJSON(json, simplifyVector = TRUE) 
#'
#' @return List of controls (each a list)
#'
#' @examples
getControls <- function(rcapConfig) {
  
  if (!is.null(rcapConfig$pages)) {
    return(unlist(lapply(rcapConfig$pages, getControlsPage), recursive=FALSE))
  } else {
    return(list())
  }
  
}

#' Parse an RCAP page for functions
#'
#' @description Process and return each control that creates an OCAP R function 
#' on a page. This function will call itself recursively for all child pages in
#' a depth first search.
#'
#' @param rcapPage a list containing the controls on a page
#'
#' @return list of the controls (each a list) on the page and the functions of child pages in
#' a tree structure.
#'
#' @examples
#' \dontrun{
#' pageFunctions <- lapply(rcapConfig$pages, getControlsPage)
#' }
getControlsPage <- function(rcapPage) {
  
  # Check for child pages
  if(!is.null(rcapPage$pages)) {
    childControls <- lapply(rcapPage$pages, getControlsPage)
  } else {
    childControls <- list()
  }
  
  # Now check for controls
  if (!is.null(rcapPage$controls)) {
    pageControls <- rcapPage$controls
  } else {
    pageControls <- list()
  }
  
  return(append(childControls, pageControls))
  
}
