
#' Return a list of all controls
#'
#' The pages of the dashboard and the controls form a hierarchy,
#' as controls can have child controls. This parser goes over the
#' hierarchy recursively, and returns a flat list containing
#' all controls.
#'
#' Each list element corresponds to a control, it is a list itself,
#' with the followinf members:
#' \itemize{
#'   \item \code{type} see \code{control_classes} for the types.
#'   \item \code{x}, \code{y} position on the grid.
#'   \item \code{width}, \code{height} size on te grid.
#'   \item \code{id} unique identifier, this is used in the protocol.
#'   \item \code{controlProperties} another list, with \code{uid},
#'     code{value} pairs, containing the configuration of the control.
#'     (E.g. labels, associated R variables, or R function, etc.)
#'   \item \code{childControls} if a control has children, they are
#'     recursively included here.
#' }
#'
#' See \preformatted{  system.file("tests", "testthat",
#'     "testConfig.json", package = "rcloud.rcap")
#' } for an example JSON file describing controls.
#' @param rcapConfig a list generated by
#'   \code{jsonlite::fromJSON}, with \code{simplifyVector = TRUE}.
#'
#' @return List of controls (each a list itself).
#'
#' @importFrom jsonlite fromJSON

getControls <- function(rcapConfig) {

  allJsonControls <- list()

  getControlsPage <- function(rcapPage) {

    # Check for child pages
    if (!is.null(rcapPage$pages)) {
      childControls <- lapply(rcapPage$pages, getControlsPage)
    } else {
      childControls <- list()
    }

    # Now check for controls
    if (!is.null(rcapPage$controls)) {
      pageControls <- lapply(rcapPage$controls, getControlsControl)
    } else {
      pageControls <- list()
    }

    append(childControls, pageControls)
  }

  getControlsControl <- function(rcapControl) {

    # Check for child controls
    if (!is.null(rcapControl$childControls)) {
      childControls <- lapply(rcapControl$childControls, getControlsControl)
    } else {
      childControls <- list()
    }

    allJsonControls <<- append(allJsonControls, list(rcapControl))

    # Append the children and return
    class(rcapControl) <- "rcapControl"
    append(childControls, list(rcapControl))
  }

  ### Start the search here
  # First data sources
  if (!is.null(rcapConfig$dataSources)) {
    lapply(rcapConfig$dataSources, getControlsControl)
  }

  # Then page controls
  if (!is.null(rcapConfig$pages)) {
    lapply(rcapConfig$pages, getControlsPage)
  }

  if (!is.null(rcapConfig$timers)) {
    lapply(rcapConfig$timers, getControlsControl)
  }
  allJsonControls
}
