
#' Parse Configuration List
#'
#' @param rcapConfig a list generated by jsonlite::fromJSON(json, simplifyVector = TRUE) 
#'
#' @return List of R function names in same hierachy as page structure
#'
#' @examples
#' jsonFile <- system.file(package = "rcloud.rcap", file="testData/testConfig.json")
#' rcapConfig <- jsonlite::fromJSON(jsonFile, simplifyVector = FALSE)
#' rcapFunctions <- parseConfig(rcapConfig)
#' 
parseConfig <- function(rcapConfig) {
  
  if (!is.null(rcapConfig$pages)) {
    return(lapply(rcapConfig$pages, parsePage))
  } else {
    return(list())
  }
  
}

#' Parse an RCAP page for functions
#'
#' @description Process and return each control that creates an OCAP R function 
#' on a page. This function will call itself recursively for all child pages in
#' a depth first search.
#'
#' @param rcapPage a list containing the controls on a page
#'
#' @return list of the functions on the page and the functions of child pages in
#' a tree structure.
#'
#' @examples
#' \dontrun{
#' pageFunctions <- lapply(rcapConfig$pages, parsePage)
#' }
parsePage <- function(rcapPage) {
  
  # Check for child pages
  if(!is.null(rcapPage$pages)) {
    childFunctions <- lapply(rcapPage$pages, parsePage)
  } else {
    childFunctions <- list()
  }
  
  # Now check for controls
  if (!is.null(rcapPage$controls)) {
    pageFunctions <- lapply(rcapPage$controls, parseControl)
  } else {
    pageFunctions <- list()
  }
  
  return(list(childFunctions=childFunctions, pageFunctions=pageFunctions))
  
}

#' Parse a control for OCAPs
#'
#' @param rcapControl List containing the control object from the site JSON.
#'
#' @return The name of the R function that is callable from the client-side (OCAP)
#'
#' @examples
#' \dontrun{
#' pageFunctions <- lapply(rcapPage$controls, parseControl)
#' }
#' 
parseControl <- function(rcapControl) {
  
  # Apply the class from the type if available
  if (!is.null(rcapControl$type)) {
    attr(rcapControl, "class") <- rcapControl$type
  }
  
  return(processControl(rcapControl))
  
}